server:
  port: 8081
spring:
  application:
    name: notification-service
  mail:
    host: smtp.mail.ru
    port: 465
    username: g
    password: 
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
