server:
  port: 8081
spring:
  application:
    name: notification-service
  mail:
    host: smtp.mail.ru
    port: 465
    username: gun_gun12@mail.ru
    password: L5kxint2EdowsMFsLw5
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          serviceBreaker:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 10s
            permittedNumberOfCallsInHalfOpenState: 3
            minimumNumberOfCalls: 5
            automaticTransitionFromOpenToHalfOpenEnabled: true
            slidingWindowType: COUNT_BASED
            registerHealthIndicator: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
